Document: pipenv
Title: Debian pipenv Manual
Author: <insert document author here>
Abstract: This manual describes what pipenv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pipenv/pipenv.sgml.gz

Format: postscript
Files: /usr/share/doc/pipenv/pipenv.ps.gz

Format: text
Files: /usr/share/doc/pipenv/pipenv.text.gz

Format: HTML
Index: /usr/share/doc/pipenv/html/index.html
Files: /usr/share/doc/pipenv/html/*.html
